baseURL = 'https://tr7zw.github.io/'
languageCode = 'en-us'
title = "tr7zw's project space"
theme = 'github-style'
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "tr7zw's project space"
  description = "Insert witty comment here"
  github = "tr7zw"
  email = "contact@tr7zw.dev"
  url = "https://tr7zw.dev"
  keywords = "blog, tr7zw, nbtapi, nbt-api, firstperson, 3d Skin Layers, 3dskinlayers, entityculling"
  rss = true
  lastmod = false
  userStatusEmoji = ""
  favicon = "/images/github.png"
  location = "Frankfurt, Germany"
  enableGitalk = false
  avatar = "/images/profile.png"
  twitter = "tr7zw"
  curseforge = "tr9zw"
  spigot = "tr7zw.27296"
  modrinth = "tr7zw"
  kofi = "tr7zw"
  discordserverid = "342814924310970398"
  discordinvite = "https://discordapp.com/invite/yk4caxM"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
