baseURL = 'https://tr7zw.github.io/'
languageCode = 'en-us'
title = "tr7zw's project space"
theme = 'github-style'
googleAnalytics = "G-H0RZ7K9HFK"
pygmentsCodeFences = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe= true

[params]
  author = "tr7zw's project space"
  description = "Developer of Minecraft Mods and Plugins. Also working and contributing to other open source projects."
  github = "tr7zw"
  email = "contact@tr7zw.dev"
  url = "https://tr7zw.dev"
  keywords = "blog, tr7zw, nbtapi, nbt-api, firstperson, 3d Skin Layers, 3dskinlayers, entityculling"
  rss = true
  lastmod = false
  userStatusEmoji = ""
  favicon = "/images/favicon.ico"
  location = "Frankfurt, Germany"
  enableGitalk = false
  avatar = "/images/profile.png"
  mastodon = "https://mastodon.social/@tr7zw"
  twitter = "tr7zw"
  curseforge = "tr9zw"
  spigot = "tr7zw.27296"
  modrinth = "tr7zw"
  kofi = "tr7zw"
  discordserverid = "342814924310970398"
  discordinvite = "https://discordapp.com/invite/yk4caxM"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
